version: '3.8'

networks:
  default:

services:

  mysql-db:
    container_name:  mysql-db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: appointments
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3308:3306
    volumes:
      - mysql-volume:/var/lib/mysql:rw
      - ./:/docker-entrypoint-initdb.d/
    networks:
      - default

  express-app:
    container_name: express-app
    depends_on:
      - mysql-db
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3001:3000
    environment:
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_PASSWORD
      - DB_DATABASE=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    networks:
      - default

volumes: 
  mysql-volume: